import Head from 'next/head';
import FormComponent from '../components/FormComponent';
import Header from '../components/Header';
import MarkdownWorkflow from '../components/MarkdownWorkflow';
import { useState } from 'react';

export default function Home() {
	const [userState, setUserState] = useState({
		introduction: {
			name: '',
			subtitle: '',
			description: '',
			email: '',
			based: '',
			portfolioLink: '',
			portfolioText: '',
			currentlylearing: '',
			anythisElse: '',
		},
		skills: [],
		socials: {
			github: '',
			instagram: '',
			twitter: '',
			hashnode: '',
			medium: '',
			devTo: '',
			linkedin: '',
			polywork: '',
			behance: '',
		},
	});

	return (
		<div className='app bg-bluishWhite'>
			<Head>
				<title>Github Profile Builder</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.png'
				/>
			</Head>

			<Header />
			<div className='box'>
				<FormComponent
					userState={userState}
					setUserState={setUserState}
				/>
				<MarkdownWorkflow
					className='markdownWorkflow'
					userState={userState}
					setUserState={setUserState}
				/>
			</div>
		</div>
	);
}
